resources:
  - name: incoming_webhook_artifact_deployed
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook
pipelines:
  - name: on_artifact_deployed
    steps:
      - name: on_artifact_deployed
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_artifact_deployed
          integrations:
            - name: artifactory_deployer
        execution:
          onStart:
            - echo "${res_incoming_webhook_artifact_deployed_payload}" > payload.json
          onExecute:
            - jfrog rt c show
            - |
              repoKey="$(read_json payload.json data.repo_key)"
              path="$(read_json payload.json data.path)"
              echo "Annotating ${repoKey}/${path}..."
              jfrog rt set-props "${repoKey}/${path}" artifact.deployed.handled=true
