resources:
  - name: incoming_webhook_artifact_deployed
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook
pipelines:
  - name: on_artifact_deployed
    steps:
      - name: on_artifact_deployed
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_artifact_deployed
        execution:
          onStart:
            - echo "${res_incoming_webhook_artifact_deployed_payload}" > payload.json
          onExecute:
            - read_json payload.json data.repo_key
            - read_json payload.json data.path
